### ISSUE TITLE
Google Mobile Ads SDK Update

### ISSUE THREAD

**Issue by mmathieum** [mtransitapps/mtransit-for-android-gradle#10]
> Starting March 2019, Google will begin releasing new versions of the Mobile Ads SDK and associated mediation adapters, which may require changes to your app.
> In an effort to streamline and simplify your workflow, Google will begin automatically initializing your ad network SDKs. If you update your application to include the new versions of these mediation adapters, you may also need to make changes to how your application initializes the Mobile Ads SDK.
> **What’s changing?**
> With these new mediation adapter versions, ads may be preloaded either by the Mobile Ads SDK or the mediation partner SDKs upon calling MobileAds.initialize() in Android and GADMobileAds.configure in iOS.
> **What are the next steps?**
> If your application is affected, make sure you take any of the following actions before initializing the Mobile Ads SDK:
> •	if you need to obtain consent from users in the European Economic Area (EEA)
> •	if you set any request-specific flags (such as tagForChildDirectedTreatment or tag_for_under_age_of_consent)
> •	or if you take any other action before loading ads

https://developers.google.com/admob/android/quick-start#initialize_mobileads

### Tasks
- [ ] Extract view logic out of ad manager
- [ ] Persist DEBUG flavor resources keys
- [x] Check Ad Lite library usage impact
- [x] Test ads displayed for non-paying users
- [x] Test ads NOT displayed for paying users
