### ISSUE TITLE
Migrate private Alpha & Beta program from Google+ to Email list & Google Group (before April 1, 2019)

### ISSUE THREAD

**Issue by mmathieum** [mtransitapps/mtransit-for-android-gradle#4]
AS a alpha/private-beta user I want to be able to keep downloading pre-release version of the apps on the Google Play Store after Google+ [Communities] are shut down on April 1, 2019.

- MonTransit Alpha Google+ Community:
https://plus.google.com/communities/106598223836498160476
- MonTransit Beta Google+ Community:
https://plus.google.com/communities/111796337224469270605
- MonTransit Beta Google Group:
https://groups.google.com/forum/#!forum/montransit-beta (montransit-beta@googlegroups.com)

### Tasks
- [x] Update wiki page: https://github.com/mtransitapps/mtransit-for-android/wiki/BETA
- [x] Update Alpha to email list
- [x] Update Beta to Google Group
- [x] Remove Google+ from Store listing
- [x] Remove Google+ from main app UI
- [x] Publish v1.1r144+ to Production
- [x] main MonTransit app
- [x] ca-airdrie-transit-bus-android
- [x] ca-banff-roam-transit-bus-android
- [x] ca-barrie-transit-bus-android
- [x] ca-brampton-transit-bus-android
- [x] ca-brandon-transit-bus-android
- [x] ca-burlington-transit-bus-android
- [x] ca-calgary-transit-bus-android
- [x] ca-calgary-transit-train-android
- [x] ca-campbell-river-transit-system-bus-android
- [x] ca-central-fraser-valley-transit-system-bus-android
- [x] ca-chambly-richelieu-carignan-citcrc-bus-android
- [x] ca-chilliwack-transit-system-bus-android
- [x] ca-comox-valley-transit-system-bus-android
- [x] ca-cornwall-transit-bus-android
- [x] ca-cowichan-valley-transit-system-bus-android
- [x] ca-cranbrook-transit-system-bus-android
- [x] ca-dawson-creek-transit-system-bus-android
- [x] ca-deux-montagnes-mrcdm-bus-android
- [x] ca-durham-region-transit-bus-android
- [x] ca-edmonton-ets-bus-android
- [x] ca-edmonton-ets-train-android
- [x] ca-fort-erie-transit-bus-android
- [x] ca-fort-st-john-transit-system-bus-android
- [x] ca-fraser-valley-express-bus-android
- [x] ca-fredericton-transit-bus-android
- [x] ca-gatineau-sto-bus-android
- [x] ca-grande-prairie-transit-bus-android
- [x] ca-grand-river-transit-bus-android
- [x] ca-gta-up-express-train-android
- [x] ca-gtha-go-transit-bus-android
- [x] ca-gtha-go-transit-train-android
- [x] ca-guelph-transit-bus-android
- [x] ca-halifax-transit-bus-android
- [x] ca-halifax-transit-ferry-android
- [x] ca-hamilton-hsr-bus-android
- [x] ca-haut-st-laurent-cithsl-bus-android
- [x] ca-joliette-ctjm-bus-android
- [x] ca-kamloops-transit-system-bus-android
- [x] ca-kelowna-regional-transit-system-bus-android
- [x] ca-kingston-transit-bus-android
- [x] ca-lanaudiere-crtl-bus-android
- [x] ca-la-presqu-ile-citpi-bus-android
- [x] ca-l-assomption-mrclasso-bus-android
- [x] ca-laurentides-citla-bus-android
- [x] ca-laval-stl-bus-android
- [x] ca-le-richelain-citlr-bus-android
- [x] ca-les-moulins-mrclm-bus-android
- [x] ca-lethbridge-transit-bus-android
- [x] ca-levis-stl-bus-android
- [x] ca-london-transit-bus-android
- [x] ca-longueuil-rtl-bus-android
- [x] ca-maritime-bus-android
- [x] ca-milton-transit-bus-android
- [x] ca-mississauga-miway-bus-android
- [x] ca-moncton-codiac-transpo-bus-android
- [x] ca-montreal-amt-bus-android
- [x] ca-montreal-amt-train-android
- [x] ca-montreal-bixi-bike-android
- [x] ca-montreal-stm-bus-android
- [x] ca-montreal-stm-subway-android
- [x] ca-nanaimo-rdn-transit-system-bus-android
- [x] ca-niagara-falls-transit-bus-android
- [x] ca-niagara-falls-wego-bus-android
- [x] ca-niagara-region-transit-bus-android
- [x] ca-oakville-transit-bus-android
- [x] ca-ottawa-oc-transpo-bus-android
- [x] ca-ottawa-oc-transpo-train-android
- [x] ca-prince-george-transit-system-bus-android
- [x] ca-quebec-orleans-express-bus-android
- [x] ca-quebec-rtc-bus-android
- [x] ca-red-deer-transit-bus-android
- [x] ca-regina-transit-bus-android
- [x] ca-richelieu-citvr-bus-android
- [x] ca-roussillon-citrous-bus-android
- [x] ca-saskatoon-transit-bus-android
- [x] ca-shawinigan-rtcs-bus-android
- [x] ca-sherbrooke-sts-bus-android
- [x] ca-sorel-varennes-citsv-bus-android
- [x] ca-squamish-transit-system-bus-android
- [x] ca-st-albert-transit-bus-android
- [x] ca-st-catharines-transit-bus-android
- [x] ca-ste-julie-omitsju-bus-android
- [x] ca-st-john-s-metrobus-transit-bus-android
- [x] ca-strathcona-county-transit-bus-android
- [x] ca-sudbury-transit-bus-android
- [x] ca-sud-ouest-citso-bus-android
- [x] ca-sunshine-coast-regional-transit-system-bus-android
- [x] ca-thunder-bay-transit-bus-android
- [x] ca-toronto-share-bike-android
- [x] ca-toronto-ttc-bus-android
- [x] ca-toronto-ttc-light-rail-android
- [x] ca-toronto-ttc-subway-android
- [x] ca-vancouver-mobi-bike-android
- [x] ca-vancouver-translink-bus-android
- [x] ca-vancouver-translink-ferry-android
- [x] ca-vancouver-translink-train-android
- [x] ca-vernon-transit-system-bus-android
- [x] ca-victoria-regional-transit-system-bus-android
- [x] ca-welland-transit-bus-android
- [x] ca-west-coast-express-bus-android
- [x] ca-west-coast-express-train-android
- [x] ca-west-kootenay-transit-system-bus-android
- [x] ca-whistler-transit-system-bus-android
- [x] ca-whitehorse-transit-bus-android
- [x] ca-windsor-transit-bus-android
- [x] ca-winnipeg-transit-bus-android
- [x] ca-york-region-yrt-viva-bus-android
- [x] us-anchorage-people-mover-bus-android
- [x] us-clark-county-c-tran-bus-android
- [x] us-everett-transit-bus-android
- [x] us-juneau-capital-transit-bus-android
- [x] us-longview-rivercities-transit-bus-android
- [x] us-snohomish-county-community-transit-bus-android
- [x] us-washington-state-ferry-android

**Comment by mmathieum** [comment]
https://github.com/mtransitapps/mtransit-for-android/tree/hotfix/remove_google_plus
