### ISSUE TITLE
#BIG Migrate to the Google Play Billing library (November 1, 2020)

### ISSUE THREAD

**Issue by mmathieum** [mtransitapps/mtransit-for-android-gradle#8]
AS a paying user I want the app to use the latest Google Play Billing library to enable secure subscriptions (and other new billing features later).

```
implementation 'com.android.billingclient:billing:3.0.0'
```

-----

https://app.circleci.com/pipelines/github/mtransitapps/mtransit-for-android-gradle?branch=feature%2Fplay_billing_library_v3

https://github.com/mtransitapps/mtransit-for-android-gradle/compare/mmathieum...feature/play_billing_library_v3

https://github.com/mtransitapps/mtransit-for-android/compare/mmathieum...feature/play_billing_library_v3

https://github.com/mtransitapps/commons-android/compare/mmathieum...feature/play_billing_library_v3

https://github.com/mtransitapps/commons/compare/mmathieum...feature/play_billing_library_v3

-----

Links: 
https://developer.android.com/google/play/billing/integrate
https://developer.android.com/google/play/billing/billing_library_releases_notes.html
https://developer.android.com/google/play/billing/billing_library.html#connecting
https://developer.android.com/google/play/billing/billing_library_overview#Verify-purchase-device

https://developer.android.com/google/play/billing
https://developer.android.com/google/play/billing/subs#restore
https://developer.android.com/google/play/billing/subs#account-hold
https://developer.android.com/google/play/billing/subs#pause
https://developer.android.com/google/play/billing/test#testing-subscriptions

https://developer.android.com/google/play/billing/rtdn-reference

https://android-developers.googleblog.com/2017/08/build-subscriptions-business-on-google.html
https://android-developers.googleblog.com/2017/06/money-made-easily-with-new-google-play.html
https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

https://www.youtube.com/watch?v=9chvh1WYCvw

https://medium.com/exploring-android/exploring-the-play-billing-library-for-android-55321f282929

https://github.com/googlesamples/android-play-billing/tree/master/TrivialDrive_v2
https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java

https://github.com/android/play-billing-samples
https://github.com/android/play-billing-samples/blob/88f347d61366086267b93fe00625d69b3ed45dbb/ClassyTaxi/firebase/server/src/play-billing/PurchasesManager.ts#L309-L328

### Tasks
- [x] use `com.android.billingclient.api`
- [x] test purchase
- [x] test ads removed
- [x] test errors (offline, cancelled)
